theme: minima
title: "My blog with Jekyll"
date: 2020-10-25
author: Astro Khan
email: masaladosa6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Это тестовое описание моего тестого блога с темой Джекил. Тут я немного напишу о ниочем,
  просто что бы занять побольше места в разделе "описание"
Ну и пожалуй добавлю еще немного ничего.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
